version: '3'
services:
  sogl-nginx:
    build: ./nginx
    tty: true
    #ports:
    #  - "80:80"
    volumes:
      - ./volume/www/var/www:/var/www
      - ./volume/www/var/log/nginx:/var/log/nginx
    depends_on:
      - python
    networks:
      - sogl
      - internal

  python:
    environment:
      DEBUG: 0
      SECRET_KEY: aaa
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn sogl.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - sogl

networks:
  sogl:
    external: true
