version: '3'
services:
  nginx:
    build: ./nginx
    tty: true
    #    ports:
    #      - "80:80"
    volumes:
      - ./volume/www/var/www:/var/www
      - ./volume/www/var/log/nginx:/var/log/nginx
    depends_on:
      - python

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - nginx
    restart: always
    environment:
      DOMAINS: 'sg-sample.aoisoft.work -> http://nginx:80'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

  python:
    environment:
      DEBUG: 0
      SECRET_KEY: aaa

volumes:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
