version: '3'
services:
  nginx:
    build: ./nginx
    tty: true
    #ports:
    #  - "80:80"
    volumes:
      - ./volume/www/var/www:/var/www
      - ./volume/www/var/log/nginx:/var/log/nginx
    depends_on:
      - python
    network:
      - sogl

  python:
    environment:
      DEBUG: 0
      SECRET_KEY: aaa
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn sogl.wsgi:application --bind 0.0.0.0:8000"

volumes:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL

networks:
  sogl:
    external: true
