# Generated by Django 4.2.16 on 2024-09-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_party_userparty_userpartymember"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserPartyMember",
            new_name="UserPartyChara",
        ),
        migrations.AlterModelTable(
            name="userpartychara",
            table="user_party_chara",
        ),
    ]
