# Generated by Django 4.2.16 on 2024-09-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_quest_userquest"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE user ADD COLUMN level INTEGER NOT NULL DEFAULT 1 AFTER name;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE user DROP COLUMN level;
                """
            ],
        ),
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE user ADD COLUMN current_stamina INTEGER NOT NULL DEFAULT 0 AFTER last_accessed_at;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE user DROP COLUMN current_stamina;
                """
            ],
        ),
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE user ADD COLUMN last_recovered_at DATETIME(6) DEFAULT NULL AFTER current_stamina;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE user DROP COLUMN last_recovered_at;
                """
            ],
        ),
    ]
