# Generated by Django 4.2.16 on 2024-09-15 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_user_current_stamina_user_last_recovered_at"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE user_quest ADD COLUMN user_id BIGINT NOT NULL DEFAULT 0 AFTER quest_id;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE user_quest DROP COLUMN user_id;
                """
            ],
        ),
    ]
