# Generated by Django 4.2.16 on 2024-09-15 05:44

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_user_quest_user_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # データベース操作は空にします
                # 既にカラムは存在しているため、ここでの操作は不要です
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="current_stamina",
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="user",
                    name="last_recovered_at",
                    field=models.DateTimeField(default=timezone.now),
                ),
                migrations.AddField(
                    model_name="user",
                    name="level",
                    field=models.IntegerField(default=1),
                ),
                migrations.AddField(
                    model_name="userquest",
                    name="user_id",
                    field=models.BigIntegerField(default=0),
                ),
            ]
        )
    ]
