# Generated by Django 4.2.16 on 2024-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_fake"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE user ADD COLUMN select_party_id BIGINT NOT NULL DEFAULT 0 AFTER last_recovered_at;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE user DROP COLUMN select_party_id;
                """
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # データベース操作は空にします
                # 既にカラムは存在しているため、ここでの操作は不要です
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="select_party_id",
                    field=models.BigIntegerField(default=1),
                ),
            ]
        )
    ]
