# Generated by Django 4.2.16 on 2024-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_user_select_party_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Present",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contents", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "present",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPresent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("present_id", models.BigIntegerField()),
                ("amount", models.IntegerField()),
                ("received_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_present",
                "abstract": False,
            },
        ),
    ]
