# Generated by Django 4.2.16 on 2024-09-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_present_userpresent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="present",
            old_name="contents",
            new_name="prizes",
        ),
    ]
