# Generated by Django 4.2.16 on 2024-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_rename_contents_present_prizes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Present",
        ),
        migrations.RemoveField(
            model_name="userpresent",
            name="present_id",
        ),
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE user_present ADD COLUMN prizes JSON DEFAULT NULL AFTER user_id;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE user_present DROP COLUMN prizes;
                """
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
            ],
            state_operations=[
                migrations.AddField(
                    model_name="userpresent",
                    name="prizes",
                    field=models.JSONField(default="[]"),
                    preserve_default=False,
                ),
            ]
        )
    ]
