# Generated by Django 4.2.16 on 2024-09-16 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_delete_present_remove_userpresent_present_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gacha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("introduction", models.CharField(max_length=1000)),
                ("display_order", models.IntegerField()),
                ("cost_type", models.CharField(max_length=100)),
                ("cost_id", models.BigIntegerField()),
                ("cost_amount", models.IntegerField()),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gacha",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GachaSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gacha_id", models.BigIntegerField()),
                (
                    "weight",
                    models.IntegerField(
                        db_comment="permyriad, 万分率",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                ("prizes", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gacha_slot",
                "abstract": False,
            },
        ),
    ]
