# Generated by Django 4.2.16 on 2024-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_gacha_gachaslot"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE gacha ADD COLUMN exec_count int DEFAULT NULL AFTER cost_amount;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE gacha DROP COLUMN exec_count;
                """
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
            ],
            state_operations=[
                migrations.AddField(
                    model_name="gacha",
                    name="exec_count",
                    field=models.IntegerField(default=1),
                ),
            ]
        )
    ]
