# Generated by Django 4.2.16 on 2024-09-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_gacha_exec_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "login_bonus",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoginBonusPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_bonus_id", models.BigIntegerField()),
                ("day", models.IntegerField()),
                ("prizes", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "login_bonus_prize",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserLoginBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("login_bonus_id", models.BigIntegerField()),
                ("day", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_login_bonus",
                "abstract": False,
            },
        ),
    ]
