# Generated by Django 4.2.16 on 2024-09-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_loginbonus_loginbonusprize_userloginbonus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "announce",
                "abstract": False,
            },
        ),
    ]
