# Generated by Django 4.2.16 on 2024-09-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_announce"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoginBonusPrize",
            new_name="LoginBonusReward",
        ),
        migrations.AlterModelTable(
            name="loginbonusreward",
            table="login_bonus_reward",
        ),
    ]
