# Generated by Django 4.2.16 on 2024-09-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_rename_loginbonusprize_loginbonusreward_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gachaslot",
            old_name="prizes",
            new_name="rewards",
        ),
        migrations.RenameField(
            model_name="loginbonusreward",
            old_name="prizes",
            new_name="rewards",
        ),
        migrations.RenameField(
            model_name="userpresent",
            old_name="prizes",
            new_name="rewards",
        ),
    ]
