# Generated by Django 4.2.16 on 2024-09-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_rename_prizes_gachaslot_rewards_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "condition_type",
                    models.CharField(
                        choices=[("login_count", "ログイン回数"), ("clear_quest", "クエストクリア")],
                        max_length=100,
                    ),
                ),
                ("condition_value", models.IntegerField()),
                ("target_amount", models.IntegerField()),
                ("rewards", models.JSONField()),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mission",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("mission_id", models.BigIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                ("is_rewarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_mission",
                "abstract": False,
                "unique_together": {("user_id", "mission_id")},
            },
        ),
    ]
