# Generated by Django 4.2.16 on 2024-09-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0020_usermission_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="description",
        ),
    ]
