# Generated by Django 4.2.16 on 2024-09-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_remove_mission_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_accessed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
