# Generated by Django 4.2.16 on 2024-09-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0022_alter_user_last_accessed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("daily_login", "ログイン"),
                            ("quest", "クエスト"),
                            ("mission_complete", "ミッション達成"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("detail", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_level", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
