# Generated by Django 4.2.16 on 2024-09-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_userlog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userlog",
            table="user_log",
        ),
    ]
