# Generated by Django 4.2.16 on 2024-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0024_alter_userlog_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
            ],
            options={
                "db_table": "event",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.BigIntegerField()),
                ("rank_from", models.IntegerField()),
                ("rank_to", models.IntegerField()),
                ("rewards", models.JSONField()),
                ("amount", models.IntegerField()),
            ],
            options={
                "db_table": "event_reward",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("event_id", models.BigIntegerField()),
                ("score", models.IntegerField(default=0)),
                ("is_rewarded", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user_event",
                "abstract": False,
                "unique_together": {("user_id", "event_id")},
            },
        ),
    ]
