# Generated by Django 4.2.16 on 2024-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0025_event_eventreward_userevent"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE quest ADD COLUMN type varchar(50) DEFAULT 'normal' AFTER name;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE quest DROP COLUMN type;
                """
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
            ],
            state_operations=[
                migrations.AddField(
                    model_name="quest",
                    name="type",
                    field=models.CharField(
                        choices=[("normal", "定常クエスト"), ("quest", "イベントクエスト")],
                        default="normal",
                        max_length=50,
                    ),
                ),
            ]
        )
    ]
