# Generated by Django 4.2.16 on 2024-09-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0026_quest_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="type",
            field=models.CharField(
                choices=[("normal", "定常クエスト"), ("event", "イベントクエスト")],
                default="normal",
                max_length=50,
            ),
        ),
    ]
