# Generated by Django 4.2.16 on 2024-09-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0028_event_created_at_event_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.BigIntegerField()),
                ("quest_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "event_quest",
                "abstract": False,
                "unique_together": {("event_id", "quest_id")},
            },
        ),
    ]
