# Generated by Django 4.2.16 on 2024-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0029_eventquest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="clear_present_id",
        ),
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE quest ADD COLUMN rewards json DEFAULT null AFTER need_stamina;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE quest DROP COLUMN rewards;
                """
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
            ],
            state_operations=[
                migrations.AddField(
                    model_name="quest",
                    name="rewards",
                    field=models.JSONField(null=True),
                ),
            ]
        )
    ]
