# Generated by Django 4.2.16 on 2024-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0030_remove_quest_clear_present_id_quest_rewards"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE event ADD COLUMN ranking_point_id bigint DEFAULT 0 AFTER description;
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE event DROP COLUMN ranking_point_id;
                """
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
            ],
            state_operations=[
                migrations.AddField(
                    model_name="event",
                    name="ranking_point_id",
                    field=models.BigIntegerField(default=0),
                    preserve_default=False,
                ),
            ]
        )
    ]
